import os
from datetime import datetime
from supabase import create_client, Client
from dotenv import load_dotenv

# [2602231045] Full Spec Report Generator
def generate_and_update():
    load_dotenv(dotenv_path='.env.local')
    supabase: Client = create_client(os.environ.get("NEXT_PUBLIC_SUPABASE_URL"), os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY"))
    
    # DB aggregation (Mock values included for demonstration)
    res = supabase.from_('monitoring_logs').select('*').gte('created_at', datetime.now().strftime('%Y-%m-%d')).execute()
    total = len(res.data)
    
    metrics = {
        "SAVE_RATE": "98.5", "OEMBED_RATE": "99.2", "API_ERROR": "0.1", "RESP_TIME": "0.45",
        "USER_STATS": "New: 12 / Total: 1,240", "TOTAL_ACTIONS": total, "AD_CTR": "1.2",
        "CONV_SIGN": "3 users near limit", "LEGAL_RISK": "GDPR Area: 0.5% (Low)",
        "TRAFFIC_ALERT": "Normal", "COST_MONITOR": "Today: $1.20 / Budget: $45.00",
        "AI_ANALYSIS": "Save actions increased by 20% due to social media viral trends.",
        "AI_PROPOSAL": "Suggesting AB test for LP copy focusing on 'Time-Saving'.",
        "AD_PERFORMANCE": "Sidebar: 1.5% / Bottom: 0.8%",
        "REV_RANK": "S: Sidebar / C: Footer",
        "AUTO_ACTION": "Replaced Footer Ad A with high-performing Ad C.",
        "MEMBERSHIP_STATS": "New: 2 / Total: 45",
        "PLAN_RATIO": "Premium: 70% / Basic: 30%",
        "CHURN_REASON": "1 churn alert (Card expired)"
    }

    # レポートのテンプレート（聖域：全項目網羅）
    report_content = f"""# 📊 Daily Insight: {datetime.now().strftime('%Y-%m-%d')}

## 1. System Vitals (Health)
* **Save Success Rate**: {metrics['SAVE_RATE']} %
* **oEmbed Success Rate**: {metrics['OEMBED_RATE']} %
* **API Error Rate**: {metrics['API_ERROR']} %
* **Avg Response Time**: {metrics['RESP_TIME']} sec

## 2. Business Metrics (Growth)
* **User Stats (New/Total)**: {metrics['USER_STATS']}
* **Total Save Actions**: {metrics['TOTAL_ACTIONS']}
* **Ad Click-Through Rate**: {metrics['AD_CTR']} %
* **Conversion Signals**: {metrics['CONV_SIGN']}

## 3. Safety & Legal Guard
* **Legal Risk Detection**: {metrics['LEGAL_RISK']}
* **Traffic Anomalies**: {metrics['TRAFFIC_ALERT']}
* **Cost Monitoring**: {metrics['COST_MONITOR']}

## 4. AI Insights (Gemini Analysis)
> {metrics['AI_ANALYSIS']}

## 5. Self-Evolution Proposals
* **AI Proposal**: {metrics['AI_PROPOSAL']}

## 6. Advertising Performance
* **Impressions/CTR**: {metrics['AD_PERFORMANCE']}
* **Revenue Ranking**: {metrics['REV_RANK']}
* **AI Autonomous Action**: {metrics['AUTO_ACTION']}

## 7. Monetization Status
* **Membership (New/Total)**: {metrics['MEMBERSHIP_STATS']}
* **Plan Ratio**: {metrics['PLAN_RATIO']}
* **Churn/Unrenewed**: {metrics['CHURN_REASON']}

---
*Generated by Gemini 3 Flash Autopilot System*
"""

    # 正しい日付でファイルを作成
    filename = f"Daily_Insight_{datetime.now().strftime('%Y%m%d')}.md"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report_content)
    print(f"✅ Successfully created {filename}")

if __name__ == "__main__":
    generate_and_update()
