@echo off
:: [2602230845] Daily Insight Automation Pipeline (Global Standard / Pure English)
chcp 65001 > nul
set PATH=%PATH%;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;%LocalAppData%\Programs\Python\Python313;%LocalAppData%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts
cd /d %~dp0

set FILENAME=Daily_Insight_%date:~0,4%%date:~5,2%%date:~8,2%.md

echo [System] Generating Pure English Template...

:: 置換キーワードを英語 (WAITING) に統一
echo # ?? Daily Insight: %date% > %FILENAME%
echo. >> %FILENAME%
echo ## 1. System Vitals >> %FILENAME%
echo * **Success Rate**: WAITING_PERCENT %% >> %FILENAME%
echo * **Response Time**: WAITING_SEC sec >> %FILENAME%
echo * **API Error Rate**: WAITING_ERROR %% >> %FILENAME%
echo. >> %FILENAME%
echo ## 2. Business Metrics >> %FILENAME%
echo * **Active Users**: WAITING_USERS >> %FILENAME%
echo * **Saved Videos**: WAITING_VIDEOS >> %FILENAME%
echo * **Retention Rate**: WAITING_RETENTION %% >> %FILENAME%
echo. >> %FILENAME%
echo ## 3. Safety Guard >> %FILENAME%
echo * **Compliance**: Verified >> %FILENAME%
echo * **Risk Detection**: WAITING_RISK >> %FILENAME%
echo. >> %FILENAME%
echo --- >> %FILENAME%
echo *Generated by Gemini 3 Flash Autopilot System* >> %FILENAME%

python analyzer.py

git add .
git commit -m "fix: [2602230845] Eliminate encoding issues by using English placeholders"
git push origin master:main

echo [Success] Report is now 100 percent encoding-safe.
pause