@echo off
:: [2602230930] Daily Insight Master Template (English Stability Mode)
chcp 65001 > nul
set PATH=%PATH%;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;%LocalAppData%\Programs\Python\Python313;%LocalAppData%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts
cd /d %~dp0

set FILENAME=Daily_Insight_%date:~0,4%%date:~5,2%%date:~8,2%.md

(
echo # ?? Daily Insight: %date%
echo.
echo ## 1. System Vitals (Health)
echo * **Save Success Rate**: WAITING_SAVE_RATE %%
echo * **oEmbed Success Rate**: WAITING_OEMBED_RATE %%
echo * **API Error Rate**: WAITING_API_ERROR %%
echo * **Avg Response Time**: WAITING_RESP_TIME sec
echo.
echo ## 2. Business Metrics (Growth)
echo * **User Stats (New/Total)**: WAITING_USER_STATS
echo * **Total Save Actions**: WAITING_TOTAL_ACTIONS
echo * **Ad Click-Through Rate**: WAITING_AD_CTR %%
echo * **Conversion Signals**: WAITING_CONV_SIGN
echo.
echo ## 3. Safety & Legal Guard
echo * **Legal Risk Detection**: WAITING_LEGAL_RISK
echo * **Traffic Anomalies**: WAITING_TRAFFIC_ALERT
echo * **Cost Monitoring**: WAITING_COST_MONITOR
echo.
echo ## 4. AI Insights (Gemini Analysis)
echo ^> WAITING_AI_ANALYSIS
echo.
echo ## 5. Self-Evolution Proposals
echo * **AI Proposal**: WAITING_AI_PROPOSAL
echo.
echo ## 6. Advertising Performance
echo * **Impressions/CTR**: WAITING_AD_PERFORMANCE
echo * **Revenue Ranking**: WAITING_REV_RANK
echo * **AI Autonomous Action**: WAITING_AUTO_ACTION
echo.
echo ## 7. Monetization Status
echo * **Membership (New/Total)**: WAITING_MEMBERSHIP_STATS
echo * **Plan Ratio**: WAITING_PLAN_RATIO
echo * **Churn/Unrenewed**: WAITING_CHURN_REASON
echo.
echo ---
echo *Generated by Gemini 3 Flash Autopilot System*
) > %FILENAME%

python analyzer.py
git add .
git commit -m "feat: complete business metrics implementation"
git push origin master:main